server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: jds
    password: 123123
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 600000
  jpa:
    hibernate:
      ddl-auto: update
